name: Setup project
description: Step to checkout and setup gradle and java
inputs:
    google-services-file:
        description: The google-services.json formatted on base64
        required: true
    secrets-properties-file:
        description: The secrets.properties formatted on base64
        required: true

runs:
  using: composite
  steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'gradle'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: ${{ github.ref != 'refs/heads/master' }}

    - name: Download google-services.json
      shell: bash
      run: echo ${{ inputs.google-services-file }} | base64 -di > app/google-services.json

    - name: Download secrets.properties
      shell: bash
      run: echo ${{ inputs.secrets-properties-file }} | base64 -di > secrets.properties
