name: Code Stability Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
            google-services-file: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
            secrets-properties-file: ${{ secrets.SECRETS_PROPERTIES_BASE64 }}

      - name: Run detekt
        run: ./gradlew detekt

      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif

      - name: Run ktlint check
        run: ./gradlew detekt

      - name: Generate Code Coverage
        uses: ./.github/actions/generate-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

      - name: Validate Snapshot tests
        run: ./gradlew verifyPaparazziDebug

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: gracker_debug_apk
          path: app/build/outputs/apk/debug/

      - name: Stop Gradle
        run: ./gradlew --stop
