name: Code Stability Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Generate Code Coverage
        uses: ./.github/actions/generate-coverage

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: gracker_debug_apk
          path: app/build/outputs/apk/debug/

      - name: Stop Gradle
        run: ./gradlew --stop