name: Main Report Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Generate Code Coverage
        uses: ./.github/actions/generate-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
