name: Main Report Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
            google-services-file: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
            secrets-properties-file: ${{ secrets.SECRETS_PROPERTIES_BASE64 }}

      - name: Generate Code Coverage
        uses: ./.github/actions/generate-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
